# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        simulation: 1
        emulation: 1
        testbed: 1
        verification: 1
        network: 1
        NPLang: 1
        p4: 1
        p4lang: 1
        fpga: 1
        consensus: 1
        PAXOS: 1
        BFT: 1
        bpf: 1
        formal method: 1
        formal verification: 1
        model check: 1
        temporal logic: 1
        TLA+: 1
        TLA: 1
        mininet: 1
        GNS3: 1

# 通知の閾値
score_threshold: 2
